# config.py
"""
Server configuration settings.
"""

import os

HOST = os.getenv("HOST", "127.0.0.1")
PORT = int(os.getenv("PORT", "8000"))
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://localhost/chrozaldb")
DB_POOL_SIZE = int(os.getenv("DB_POOL_SIZE", "10"))
PUBLIC_ORIGIN = os.getenv("PUBLIC_ORIGIN", "http://localhost:8000").rstrip("/")
COOKIE_SECURE = PUBLIC_ORIGIN.startswith("https://")
MAX_PLAYERS = int(os.getenv("MAX_PLAYERS", "100"))
ALLOW_REGISTRATION = os.getenv("ALLOW_REGISTRATION", "false").lower() == "true"
ENCODING = "utf-8" # Encoding for network communication

# --- Game Loop & Save ---
TICKER_INTERVAL_SECONDS = 1.0     # How often the main game loop runs.
AUTOSAVE_INTERVAL_SECONDS = int(os.getenv("AUTOSAVE_INTERVAL_SECONDS", "30"))

# --- Leveling & XP ---
MAX_LEVEL = 99
XP_BASE = 1000
XP_EXPONENT = 2.2
XP_ABSORB_RATE_PER_SEC = 5.0 # 600 hours of node absorption to reach level 75
SKILL_POINTS_PER_LEVEL = 5

# --- Regen Rates (Points per Second) ---
HP_REGEN_BASE_PER_SEC = 0.005
HP_REGEN_VIT_MULTIPLIER = 0.004
ESSENCE_REGEN_BASE_PER_SEC = 0.001
ESSENCE_REGEN_AURA_MULTIPLIER = 0.003
NODE_REGEN_MULTIPLIER = 2.0
MEDITATE_REGEN_MULTIPLIER = 3.0

BASE_CARRY_WEIGHT = 20.0
CARRY_WEIGHT_MIGHT_MULTIPLIER = 1.5

# --- Gameplay ---
DEFAULT_RESPAWN_ROOM_ID = 1
FALLBACK_RESPAWN_ROOM_ID = 1
STARTING_COINAGE = 125

# --- Input ---
MAX_INPUT_LENGTH = 512

# Item cleanup
ITEM_DECAY_TIME_SECONDS = 1800

AMBIENT_SCRIPT_CHANCE_PER_TICK = 0.01
# Defaults for DB-driven tuning before a world is loaded.
XP_LEVEL_75_TOTAL=10_800_000
XP_AFTER_75_GROWTH=1.18
TECHNIQUE_BASE=4
TECHNIQUE_PER_LEVEL=2
TECHNIQUE_SIGNATURE_COST=4
TECHNIQUE_FINALE_COST=8
TECHNIQUE_SIGNATURE_MULTIPLIER=1.45
TECHNIQUE_FINALE_MULTIPLIER=2
MOB_XP_BASE=25
MUD_ROUNDTIME=1.5
SNOW_ROUNDTIME=1
TETHER_XP_PER_LEVEL=250
TETHER_XP_PER_MISSING=1000
