version: '3.8'

services:
  # This is our main development environment
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # This links your project code into the environment
      - .:/workspaces/${localWorkspaceFolderBasename}:cached
    
    # --- ADD THIS LINE ---
    # This tells Codespaces to run as the standard 'vscode' non-root user.
    user: vscode

    command: sleep infinity
    depends_on:
      - db

  # This is our PostgreSQL database service
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chrozal
      - POSTGRES_PASSWORD=timcp313 # Use the password you chose before
      - POSTGRES_DB=chrozaldb

volumes:
  postgres-data: