ALTER TABLE characters ALTER COLUMN xp_total TYPE DOUBLE PRECISION;
ALTER TABLE characters ALTER COLUMN xp_pool TYPE DOUBLE PRECISION;
UPDATE characters SET level=99 WHERE level>99;
ALTER TABLE characters ADD CONSTRAINT maximum_character_level CHECK(level BETWEEN 1 AND 99);
ALTER TABLE characters ALTER COLUMN hunger TYPE DOUBLE PRECISION;
ALTER TABLE characters ALTER COLUMN thirst TYPE DOUBLE PRECISION;
